SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
    FROM FIRST_HALF
    GROUP BY FLAVOR
    
    UNION ALL
    
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
    FROM JULY
    GROUP BY FLAVOR
) AS CombinedOrders
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_SUM) DESC
LIMIT 3;
